import { useMemo, useState } from "react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { AlertTriangle, ArrowDown, ArrowRight, Boxes, BrainCircuit, Check, CircleDot, CloudSnow, Cpu, Fuel, GitBranch, Link2, Map, MessageSquare, Package, Play, Radio, ShieldAlert, Snowflake, Thermometer, Users, Wrench, Zap } from "lucide-react";

const SCENARIOS = [
  { id: "weather", label: "Weather worsens", detail: "+30% severity", readiness: -12, outputs: ["Fuel reserve -12%", "Food reserve -2.4 days", "Task delay +16 hours", "Emergency risk +21%"] },
  { id: "cargo", label: "Cargo delayed", detail: "+18 hours", readiness: -5, outputs: ["Critical cargo arrival +18 hours", "Medical reserve -4%", "Resupply route reprioritized", "Emergency risk +8%"] },
  { id: "personnel", label: "Personnel unavailable", detail: "-1 available", readiness: -6, outputs: ["Team capacity -8%", "Task load +12%", "Route lead reassignment", "Emergency risk +7%"] },
  { id: "generator", label: "Generator failure", detail: "Station B", readiness: -18, outputs: ["Power availability -35%", "Cold storage at risk", "Personnel safety risk +24%", "Resupply required"] },
  { id: "comms", label: "Communication loss", detail: "45 minutes", readiness: -7, outputs: ["Uplink unavailable", "Offline mode activated", "GPS sync delayed", "Emergency response latency +18 min"] },
];

const CONFLICTS = [
  { resource: "Generator G-04", icon: Zap, requested: ["Expedition A — 14:00", "Expedition B — 15:00"], detail: "Only 1 unit available.", options: ["Delay Expedition B → 3 hours", "Move backup generator → Station B", "Reassign Generator G-06"] },
  { resource: "Snow Vehicle V-07", icon: Snowflake, requested: ["Expedition A — 13:30", "Expedition B — 15:00"], detail: "Transit overlap is 45 minutes.", options: ["Stage V-07 at Bharati", "Use Vehicle V-03 for Expedition B", "Shift Expedition A departure → 30 min"] },
  { resource: "Medical Team M-02", icon: ShieldAlert, requested: ["Expedition A — 16:00", "Emergency standby — 16:00"], detail: "Response coverage drops below safe level.", options: ["Assign SAR Alpha backup", "Move medical team handover", "Hold Expedition A departure"] },
];

const CHAIN = [
  ["Generator failure", "Equipment fault", Zap], ["Power loss", "Station systems", Cpu], ["Heating capacity ↓", "Environmental control", Thermometer], ["Personnel safety risk ↑", "People", Users], ["Medical risk ↑", "Health reserve", ShieldAlert], ["Expedition delay", "Mission plan", Map], ["Food / fuel use ↑", "Inventory", Fuel], ["Resupply required", "Logistics action", Package],
];

const THREATS = [
  { rank: 1, label: "Fuel shortage", impact: "HIGH", detail: "Fuel coverage at Bharati is below the mission envelope.", source: "Inventory → Expedition → Risk" },
  { rank: 2, label: "Weather deterioration", impact: "HIGH", detail: "Wind trend increases route exposure in the next 18 hours.", source: "Weather → Route → Risk" },
  { rank: 3, label: "Cargo delay", impact: "MEDIUM", detail: "Medical manifest is still in transit to Station B.", source: "Cargo → Medical → Readiness" },
  { rank: 4, label: "Personnel workload", impact: "MEDIUM", detail: "One assigned task is overdue and affects departure readiness.", source: "Personnel → Tasks → Expedition" },
];

export default function CommandIntelligenceLab() {
  const [selected, setSelected] = useState(["weather"]);
  const [simulation, setSimulation] = useState(null);
  const [resolved, setResolved] = useState([]);
  const [chainActive, setChainActive] = useState(false);
  const [activeThreat, setActiveThreat] = useState(null);
  const toggleScenario = id => setSelected(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id]);
  const runSimulation = () => {
    const chosen = SCENARIOS.filter(item => selected.includes(item.id));
    const readiness = Math.max(18, 82 + chosen.reduce((sum, item) => sum + item.readiness, 0));
    setSimulation({ readiness, chosen, outputs: chosen.flatMap(item => item.outputs).slice(0, 8) });
    toast.success(`Combined scenario simulated · readiness ${readiness}%`);
  };
  const unresolved = CONFLICTS.filter(item => !resolved.includes(item.resource));
  const threat = activeThreat ? THREATS.find(item => item.rank === activeThreat) : null;
  const graph = useMemo(() => [{ label: "EXPEDITION P-001", icon: Map, tone: "cyan" }, { label: "PEOPLE", icon: Users, tone: "indigo" }, { label: "CARGO", icon: Boxes, tone: "sky" }, { label: "ROUTE", icon: Map, tone: "emerald" }, { label: "TASKS", icon: Check, tone: "amber" }, { label: "INVENTORY", icon: Package, tone: "orange" }, { label: "WEATHER", icon: CloudSnow, tone: "sky" }, { label: "RISK", icon: AlertTriangle, tone: "rose" }, { label: "EMERGENCY", icon: ShieldAlert, tone: "rose" }], []);
  return <div className="p-4 md:p-8 space-y-6">
    <div className="flex items-start justify-between flex-wrap gap-4"><div><div className="text-[10px] font-mono-tel uppercase tracking-[.2em] text-slate-500">Module · 10 / Decision support</div><h1 className="font-display text-2xl md:text-3xl font-bold text-cyan-100 mt-2">Command Intelligence Lab</h1><p className="text-sm text-slate-400 mt-1">Explore combined scenarios, detect resource conflicts, and trace cross-module threats before they become incidents.</p></div><Badge variant="outline" className="border-cyan-500/40 text-cyan-300"><BrainCircuit className="h-3.5 w-3.5 mr-1.5" />Connected intelligence graph</Badge></div>
    <section className="rounded-2xl border border-indigo-500/25 bg-indigo-500/[.035] p-5 md:p-6"><div className="flex items-start justify-between gap-4 flex-wrap"><div><div className="text-[10px] font-mono-tel uppercase tracking-widest text-indigo-300">01 · What-if decision engine</div><h2 className="font-display text-xl font-bold mt-1">What-If Lab</h2><p className="text-xs text-slate-500 mt-1">Ask “what happens if I change this decision?” and see the combined effect.</p></div><Button onClick={runSimulation} className="bg-indigo-500 hover:bg-indigo-400 text-white"><Play className="h-4 w-4 mr-2" />Run simulation</Button></div><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-5 gap-2 mt-5">{SCENARIOS.map(item => <label key={item.id} className={`rounded-xl border p-3 cursor-pointer transition-colors ${selected.includes(item.id) ? "border-indigo-400/50 bg-indigo-500/10" : "border-slate-800 bg-slate-950/50 hover:border-slate-700"}`}><div className="flex gap-2"><input type="checkbox" checked={selected.includes(item.id)} onChange={() => toggleScenario(item.id)} className="mt-1 accent-indigo-400" /><div><div className="text-xs font-semibold text-slate-200">{item.label}</div><div className="text-[10px] text-slate-500 mt-1">{item.detail}</div></div></div></label>)}</div>{simulation && <div className="mt-5 grid grid-cols-1 xl:grid-cols-[.8fr_1.2fr] gap-4"><div className="rounded-xl border border-slate-800 bg-slate-950/70 p-5"><div className="text-[10px] uppercase tracking-widest text-slate-500">Current expedition</div><div className="font-mono-tel text-4xl font-bold text-emerald-300 mt-2">82%</div><div className="text-xs text-slate-500 mt-1">POL-26-041 readiness</div><ArrowDown className="h-5 w-5 text-rose-300 my-3" /><div className="text-[10px] uppercase tracking-widest text-slate-500">Simulated readiness</div><div className="font-mono-tel text-4xl font-bold text-rose-300 mt-2">{simulation.readiness}%</div><Progress value={simulation.readiness} className="h-2 mt-4" /></div><div className="rounded-xl border border-indigo-500/25 bg-slate-950/70 p-5"><div className="flex items-center justify-between"><div><div className="text-[10px] uppercase tracking-widest text-indigo-300">Combined effect</div><div className="text-sm text-slate-300 mt-1">{simulation.chosen.length} scenario(s) active</div></div><Badge variant="outline" className="border-rose-500/40 text-rose-300">DECISION REVIEW</Badge></div><div className="grid grid-cols-1 md:grid-cols-2 gap-2 mt-4">{simulation.outputs.map(output => <div key={output} className="rounded-lg border border-slate-800 px-3 py-2 text-xs text-slate-300 flex items-center gap-2"><ArrowRight className="h-3 w-3 text-indigo-300" />{output}</div>)}</div></div></div>}</section>
    <section className="rounded-2xl border border-amber-500/25 bg-amber-500/[.03] p-5"><div className="flex items-start justify-between gap-4 flex-wrap"><div><div className="text-[10px] font-mono-tel uppercase tracking-widest text-amber-300">02 · Allocation intelligence</div><h2 className="font-display text-xl font-bold mt-1">Resource Conflict Detector</h2><p className="text-xs text-slate-500 mt-1">POLAR detects when expeditions, emergencies, and tasks request the same scarce asset.</p></div><Badge variant="outline" className="border-amber-500/40 text-amber-300">{unresolved.length} conflicts open</Badge></div><div className="mt-5 space-y-3">{CONFLICTS.map(conflict => { const Icon = conflict.icon; const done = resolved.includes(conflict.resource); return <div key={conflict.resource} className={`rounded-xl border p-4 ${done ? "border-emerald-500/25 bg-emerald-500/[.03]" : "border-slate-800 bg-slate-950/60"}`}><div className="flex items-start gap-3"><div className={`rounded-lg p-2 ${done ? "bg-emerald-500/15 text-emerald-300" : "bg-amber-500/15 text-amber-300"}`}>{done ? <Check className="h-4 w-4" /> : <Icon className="h-4 w-4" />}</div><div className="flex-1"><div className="flex items-center gap-2"><div className="font-semibold text-slate-100">{conflict.resource}</div><Badge variant="outline" className={done ? "border-emerald-500/40 text-emerald-300" : "border-amber-500/40 text-amber-300"}>{done ? "RESOLVED" : "CONFLICT"}</Badge></div><div className="text-xs text-slate-400 mt-2">Requested by: {conflict.requested.join(" · ")}</div><div className="text-xs text-slate-500 mt-1">{conflict.detail}</div><div className="flex flex-wrap gap-2 mt-3">{conflict.options.map(option => <Button key={option} size="sm" variant="outline" disabled={done} onClick={() => { setResolved(items => [...items, conflict.resource]); toast.success(`${conflict.resource}: ${option}`); }} className="border-slate-700 text-slate-300 hover:border-amber-400/50">{option}</Button>)}</div></div></div></div>; })}</div></section>
    <section className="rounded-2xl border border-rose-500/25 bg-rose-500/[.025] p-5"><div className="flex items-start justify-between gap-4 flex-wrap"><div><div className="text-[10px] font-mono-tel uppercase tracking-widest text-rose-300">03 · Mission chain reaction</div><h2 className="font-display text-xl font-bold mt-1">Impact graph</h2><p className="text-xs text-slate-500 mt-1">Select an initiating failure to visualize affected personnel, inventory, equipment, tasks, route, and emergency resources.</p></div><Button onClick={() => setChainActive(value => !value)} className={chainActive ? "bg-rose-500 hover:bg-rose-400 text-white" : "bg-slate-800 hover:bg-slate-700 text-slate-100"}><GitBranch className="h-4 w-4 mr-2" />{chainActive ? "Failure simulated" : "Simulate Generator G-04 failure"}</Button></div><div className="mt-5 flex flex-col items-center">{CHAIN.map(([label, detail, Icon], index) => <div key={label} className="flex flex-col items-center"><div className={`w-full max-w-xl rounded-xl border p-3 flex items-center gap-3 transition-all ${chainActive ? index === 0 || index === 1 || index === 3 || index === 4 || index === 7 ? "border-rose-500/50 bg-rose-500/[.08]" : "border-orange-500/30 bg-orange-500/[.04]" : "border-slate-800 bg-slate-950/60"}`}><div className="rounded-lg bg-slate-900 p-2"><Icon className="h-4 w-4 text-rose-300" /></div><div className="flex-1"><div className="text-sm font-semibold text-slate-200">{label}</div><div className="text-[10px] text-slate-500 mt-0.5">{detail}</div></div>{chainActive && <Badge variant="outline" className="border-rose-500/40 text-rose-300">AFFECTED</Badge>}</div>{index < CHAIN.length - 1 && <ArrowDown className={`h-4 w-4 my-1 ${chainActive ? "text-rose-300" : "text-slate-700"}`} />}</div>)}</div></section>
    <section className="rounded-2xl border border-cyan-500/20 bg-slate-950/60 p-5"><div className="flex items-start justify-between gap-4 flex-wrap"><div><div className="text-[10px] font-mono-tel uppercase tracking-widest text-cyan-300">04 · Cross-module intelligence</div><h2 className="font-display text-xl font-bold mt-1">Operational relationship graph</h2><p className="text-xs text-slate-500 mt-1">POLAR connects expedition, people, cargo, route, tasks, inventory, weather, risk, and emergency response.</p></div><Badge variant="outline" className="border-cyan-500/40 text-cyan-300"><Link2 className="h-3 w-3 mr-1" />9 connected domains</Badge></div><div className="mt-5 grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-2">{graph.map((node, index) => { const Icon = node.icon; return <div key={node.label} className={`rounded-xl border p-3 ${node.tone === "rose" ? "border-rose-500/30 bg-rose-500/[.05]" : node.tone === "cyan" ? "border-cyan-500/30 bg-cyan-500/[.05]" : "border-slate-800 bg-slate-950/50"}`}><Icon className={`h-4 w-4 ${node.tone === "rose" ? "text-rose-300" : node.tone === "cyan" ? "text-cyan-300" : "text-slate-400"}`} /><div className="font-mono-tel text-[10px] text-slate-300 mt-2">{node.label}</div>{index < graph.length - 1 && <div className="text-[9px] text-slate-600 mt-2">connected ↓</div>}</div>; })}</div><div className="mt-5 rounded-xl border border-rose-500/25 bg-rose-500/[.04] p-4"><div className="flex items-center gap-2 text-[10px] font-mono-tel uppercase tracking-widest text-rose-300"><AlertTriangle className="h-3.5 w-3.5" />Top operational threats to Expedition P-001</div><div className="mt-3 space-y-2">{THREATS.map(item => <button key={item.rank} onClick={() => setActiveThreat(activeThreat === item.rank ? null : item.rank)} className="w-full text-left rounded-lg border border-slate-800 bg-slate-950/60 px-3 py-2 flex items-center gap-3 hover:border-rose-500/30"><span className="font-mono-tel text-xs text-rose-300">0{item.rank}</span><span className="text-xs font-semibold text-slate-200 flex-1">{item.label}</span><Badge variant="outline" className={item.impact === "HIGH" ? "border-rose-500/40 text-rose-300" : "border-amber-500/40 text-amber-300"}>{item.impact}</Badge></button>)}</div>{threat && <div className="mt-3 rounded-lg border border-rose-500/25 bg-slate-950/70 p-3"><div className="text-sm font-semibold text-slate-100">{threat.label}</div><div className="text-xs text-slate-400 mt-1">{threat.detail}</div><div className="text-[10px] font-mono-tel text-cyan-300 mt-2">Trace: {threat.source}</div></div>}</div></section>
  </div>;
}
