import { useMemo } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Activity, ArrowDown, BrainCircuit, Check, ChevronRight, GitBranch, History, ShieldCheck, SlidersHorizontal, Sparkles } from "lucide-react";

const SIGNALS = [
  ["Weather disruption", "Route B / P-104", "Increase weather-delay weight by 12%", "READY"],
  ["Cargo delay", "Fuel transfer", "Extend arrival variance band by 3 hours", "READY"],
  ["Fuel overuse", "Southern Ice Core Survey", "Raise consumption alert threshold sensitivity", "REVIEW"],
];
const HISTORY = [
  ["Model feedback accepted", "Route B weather + cargo interaction", "Today · 10:42 UTC"],
  ["Validation completed", "P-104 prediction vs actual comparison", "Yesterday · 16:45 UTC"],
  ["Baseline snapshot", "POLAR risk model v1.4 demo dataset", "12 Sep 2026 · 09:00 UTC"],
];

export default function LearningLoop() {
  const navigate = useNavigate();
  const [params] = useSearchParams();
  const linked = params.get("feedback");
  const ready = useMemo(() => SIGNALS.filter(item => item[3] === "READY").length, []);
  return <div className="p-4 md:p-8 space-y-6">
    <div className="flex items-start justify-between gap-4 flex-wrap"><div><div className="text-[10px] font-mono-tel uppercase tracking-[.2em] text-slate-500">Module · Learning loop</div><h1 className="font-display text-2xl md:text-3xl font-bold text-violet-100 mt-2">POLAR Learning Loop</h1><p className="text-sm text-slate-400 mt-1">A transparent handoff from real mission outcomes to reviewed, explainable model improvements.</p></div><Badge variant="outline" className="border-emerald-500/40 text-emerald-300"><ShieldCheck className="h-3.5 w-3.5 mr-1.5" />Human review required</Badge></div>
    {linked && <div className="rounded-xl border border-emerald-500/25 bg-emerald-500/[.06] p-4 text-sm text-emerald-100"><Check className="inline h-4 w-4 mr-2 text-emerald-300" />Feedback item <span className="font-mono-tel">#{linked}</span> is linked to this learning-loop review.</div>}
    <section className="rounded-2xl border border-violet-500/25 bg-violet-500/[.03] p-5"><div className="flex items-start justify-between gap-4 flex-wrap"><div><div className="text-[10px] uppercase tracking-widest text-violet-300">01 · Signal pipeline</div><h2 className="font-display text-xl font-bold text-white mt-1">Outcome → review → improvement</h2></div><div className="text-right"><div className="font-mono-tel text-3xl text-violet-300">{ready}</div><div className="text-[10px] uppercase tracking-widest text-slate-500">signals ready</div></div></div><div className="grid grid-cols-2 md:grid-cols-5 gap-2 mt-5">{[["Mission outcome", History],["Operational signal", Activity],["Human review", ShieldCheck],["Model adjustment", SlidersHorizontal],["Future prediction", Sparkles]].map(([label, Icon], index) => <div key={label} className="relative rounded-xl border border-slate-800 bg-slate-950/60 p-3 text-center"><Icon className="h-4 w-4 mx-auto text-violet-300" /><div className="text-[10px] text-slate-300 mt-2">{label}</div>{index < 4 && <ChevronRight className="hidden md:block absolute -right-3 top-7 h-4 w-4 text-violet-300 z-10" />}</div>)}</div></section>
    <div className="grid grid-cols-1 xl:grid-cols-[1.2fr_.8fr] gap-5"><section className="rounded-2xl border border-slate-800 bg-slate-950/50 p-5"><div className="flex items-center justify-between"><div><div className="text-[10px] uppercase tracking-widest text-violet-300">02 · Review queue</div><h2 className="font-display text-xl font-bold text-white mt-1">Signals awaiting command approval</h2></div><Button variant="outline" onClick={() => navigate("/feedback")} className="border-cyan-500/35 text-cyan-200">Open feedback center</Button></div><div className="mt-4 space-y-3">{SIGNALS.map(([title, source, action, status]) => <div key={title} className="rounded-xl border border-slate-800 bg-slate-950/70 p-4"><div className="flex items-center gap-3"><div className="h-9 w-9 rounded-lg bg-violet-500/10 grid place-items-center"><BrainCircuit className="h-4 w-4 text-violet-300" /></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2 flex-wrap"><h3 className="text-sm font-semibold text-slate-100">{title}</h3><Badge variant="outline" className={status === "READY" ? "border-emerald-500/40 text-emerald-300" : "border-amber-500/40 text-amber-300"}>{status}</Badge></div><div className="text-[10px] uppercase tracking-widest text-slate-500 mt-1">{source}</div></div></div><div className="ml-12 mt-3 text-xs text-slate-300"><span className="text-violet-300">Proposed adjustment:</span> {action}</div><div className="ml-12 mt-3 flex gap-2"><Button size="sm" className="bg-violet-500 hover:bg-violet-400 text-white"><Check className="h-3.5 w-3.5 mr-1.5" />Review signal</Button><button className="text-xs text-slate-500 hover:text-slate-300">See evidence <ChevronRight className="inline h-3 w-3" /></button></div></div>)}</div></section><section className="rounded-2xl border border-slate-800 bg-slate-950/50 p-5"><div className="text-[10px] uppercase tracking-widest text-slate-500">03 · Applied history</div><h2 className="font-display text-xl font-bold text-white mt-1">Learning record</h2><div className="mt-4 space-y-4">{HISTORY.map(([title, detail, time]) => <div key={title} className="flex gap-3"><div className="mt-1 h-7 w-7 rounded-full border border-emerald-500/35 bg-emerald-500/10 grid place-items-center shrink-0"><Check className="h-3.5 w-3.5 text-emerald-300" /></div><div><div className="text-sm font-semibold text-slate-200">{title}</div><div className="text-xs text-slate-400 mt-1">{detail}</div><div className="text-[10px] font-mono-tel uppercase tracking-widest text-slate-600 mt-1">{time}</div></div></div>)}</div><div className="mt-6 rounded-xl border border-violet-500/25 bg-violet-500/[.05] p-4 text-xs text-slate-300"><GitBranch className="inline h-4 w-4 text-violet-300 mr-2" />No model change is applied without a command review. Every accepted adjustment is versioned and traceable.</div></section></div>
    <section className="rounded-2xl border border-cyan-500/25 bg-cyan-500/[.03] p-5"><div className="flex items-center gap-3"><div className="h-10 w-10 rounded-xl bg-cyan-500/10 grid place-items-center"><ArrowDown className="h-5 w-5 text-cyan-300" /></div><div><h2 className="font-display text-lg font-bold text-white">Next step</h2><p className="text-xs text-slate-400 mt-1">Review the highest-impact signal, then return to Mission Analytics to compare future predictions against reality.</p></div><Button onClick={() => navigate("/mission-analytics")} className="ml-auto bg-cyan-500 hover:bg-cyan-400 text-slate-950">Open Mission Analytics</Button></div></section>
  </div>;
}
