import { useEffect, useMemo, useState } from "react";
import { api } from "@/lib/api";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { AlertTriangle, ArrowDown, Battery, Check, ChevronRight, CircleDot, ClipboardCheck, CloudSnow, Database, Factory, Fuel, Gauge, GitBranch, MapPin, Package, Radio, ShieldAlert, Target, Thermometer, Truck, Users, Wrench, Zap } from "lucide-react";

const TREE = [
  { id: "mission", label: "MISSION", icon: Target, children: [{ id: "personnel", label: "Personnel", icon: Users, children: [{ id: "medical-team", label: "Medical Team", icon: ShieldAlert, detail: "12 personnel supported · response coverage stable" }, { id: "engineering-team", label: "Engineering Team", icon: Wrench, detail: "Generator inspection capability · 2 assigned" }] }, { id: "logistics", label: "Logistics", icon: Truck, children: [{ id: "food", label: "Food", icon: Package, detail: "18-day reserve · sufficient" }, { id: "fuel", label: "Fuel", icon: Fuel, detail: "9-day reserve · early warning active" }, { id: "medical-supplies", label: "Medical Supplies", icon: ShieldAlert, detail: "14-day reserve · resupply in transit" }] }, { id: "equipment", label: "Equipment", icon: Factory, children: [{ id: "generator", label: "Generator", icon: Zap, detail: "GENERATOR-07 · risk 76%" }, { id: "vehicles", label: "Vehicles", icon: Truck, detail: "V-07 route assigned · availability 92%" }] }, { id: "research", label: "Research", icon: Database, children: [{ id: "sampling", label: "Sampling", icon: MapPin, detail: "Climate sampling equipment staged" }, { id: "data", label: "Data Collection", icon: Database, detail: "Last upload 3 hours ago" }] }] },
];
const OBJECTIVES = [
  { id: "climate", label: "Climate samples", progress: 82, owner: "Research Team Alpha", status: "ON TRACK", detail: "18 of 22 sample sites complete", eta: "5 days remaining" },
  { id: "glacial", label: "Glacial measurements", progress: 61, owner: "Research Team Beta", status: "AT RISK", detail: "Weather delay affecting traverse window", eta: "+2.4 days expected" },
  { id: "weather", label: "Weather observations", progress: 91, owner: "Field Operations", status: "ON TRACK", detail: "Continuous station data captured", eta: "3 days remaining" },
  { id: "upload", label: "Research data upload", progress: 42, owner: "Communications", status: "WATCH", detail: "Next high-bandwidth window in 18 hours", eta: "+0.8 days expected" },
];
const DEPENDENCIES = { generator: { label: "GENERATOR-07", required: ["Heating", "Medical storage", "Communication", "Research equipment"], affected: 4, critical: true }, fuel: { label: "FUEL RESERVE", required: ["Tracked vehicles", "Generator runtime", "Heating", "Return route"], affected: 4, critical: true }, "medical-supplies": { label: "MEDICAL SUPPLIES", required: ["Personnel safety", "Remote traverse", "Emergency response"], affected: 3, critical: true }, "engineering-team": { label: "ENGINEERING TEAM", required: ["Generator maintenance", "Vehicle recovery", "Camp systems"], affected: 3, critical: false } };

export default function MissionSuccessMonitor() {
  const [expeditions, setExpeditions] = useState([]);
  const [selectedExpedition, setSelectedExpedition] = useState("");
  const [selected, setSelected] = useState("generator");
  const [expanded, setExpanded] = useState({ mission: true, personnel: true, logistics: true, equipment: true, research: true });
  const [objectiveFilter, setObjectiveFilter] = useState("ALL");
  const [objective, setObjective] = useState(null);
  const dependency = DEPENDENCIES[selected];
  useEffect(() => { api.get("/expeditions").then(result => { const rows = result.data || []; setExpeditions(rows); if (rows.length) setSelectedExpedition(String(rows[0].id)); }).catch(() => {}); }, []);
  const visibleObjectives = useMemo(() => objectiveFilter === "ALL" ? OBJECTIVES : OBJECTIVES.filter(item => item.status === objectiveFilter), [objectiveFilter]);
  const toggle = id => setExpanded(current => ({ ...current, [id]: !current[id] }));
  return <div className="p-4 md:p-8 space-y-6">
    <div className="flex items-start justify-between flex-wrap gap-4"><div><div className="text-[10px] font-mono-tel uppercase tracking-[.2em] text-slate-500">Module · 14 / Mission success</div><h1 className="font-display text-2xl md:text-3xl font-bold text-amber-100 mt-2">Mission Success Monitor</h1><p className="text-sm text-slate-400 mt-1">Understand what each asset means to the mission and track whether the expedition is achieving its actual objectives.</p></div><div className="flex items-center gap-3"><select aria-label="Select expedition" value={selectedExpedition} onChange={event => setSelectedExpedition(event.target.value)} className="rounded-lg border border-amber-500/30 bg-slate-950 px-3 py-2 text-xs text-slate-200"><option value="">Select expedition</option>{expeditions.map(item => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select><Badge variant="outline" className="border-amber-500/40 text-amber-300"><Target className="h-3.5 w-3.5 mr-1.5" />Objective-aware command view</Badge></div></div>
    <section className="rounded-2xl border border-cyan-500/25 bg-cyan-500/[.03] p-5 md:p-6"><div className="flex items-start justify-between gap-4 flex-wrap"><div><div className="text-[10px] font-mono-tel uppercase tracking-widest text-cyan-300">01 · Mission dependency engine</div><h2 className="font-display text-xl font-bold mt-1 flex items-center gap-2"><GitBranch className="h-5 w-5 text-cyan-300" />What does this asset mean to the mission?</h2><p className="text-xs text-slate-500 mt-1">Select any node to see the mission functions that depend on it.</p></div><Badge variant="outline" className="border-cyan-500/40 text-cyan-300">Interactive dependency tree</Badge></div><div className="grid grid-cols-1 xl:grid-cols-[1.15fr_.85fr] gap-5 mt-5"><div className="rounded-xl border border-slate-800 bg-slate-950/60 p-4">{TREE.map(root => <TreeNode key={root.id} node={root} depth={0} expanded={expanded} selected={selected} onSelect={setSelected} onToggle={toggle} />)}</div><div className="rounded-xl border border-slate-800 bg-slate-950/60 p-5 h-fit">{dependency ? <><div className="text-[10px] uppercase tracking-widest text-cyan-300">Selected dependency</div><h3 className="font-display text-xl font-bold text-slate-100 mt-2">{dependency.label}</h3><Badge variant="outline" className={dependency.critical ? "border-rose-500/40 text-rose-300 mt-3" : "border-amber-500/40 text-amber-300 mt-3"}>{dependency.critical ? "MISSION CRITICAL" : "MISSION SUPPORT"}</Badge><div className="mt-5 text-sm text-slate-300">Required by:</div><div className="mt-2 space-y-2">{dependency.required.map(item => <div key={item} className="rounded-lg border border-slate-800 p-3 text-xs text-slate-300"><Check className="inline h-3.5 w-3.5 text-emerald-300 mr-2" />{item}</div>)}</div><div className="mt-5 rounded-xl border border-rose-500/25 bg-rose-500/[.05] p-4"><div className="font-mono-tel text-3xl font-bold text-rose-300">{dependency.affected}</div><div className="text-[10px] uppercase tracking-widest text-slate-500 mt-1">mission functions affected if unavailable</div></div><Button onClick={() => toast.success(`${dependency.label} impact packet opened`)} className="w-full mt-4 bg-cyan-500 hover:bg-cyan-400 text-slate-950"><Gauge className="h-4 w-4 mr-2" />Open impact packet</Button></> : <div className="text-sm text-slate-500">Select a leaf node such as Generator or Fuel to inspect mission dependency.</div>}</div></div></section>
    <section className="rounded-2xl border border-amber-500/25 bg-amber-500/[.035] p-5 md:p-6"><div className="flex items-start justify-between gap-4 flex-wrap"><div><div className="text-[10px] font-mono-tel uppercase tracking-widest text-amber-300">02 · Mission objective tracking</div><h2 className="font-display text-xl font-bold mt-1">What is the expedition trying to accomplish?</h2><p className="text-xs text-slate-500 mt-1">POLAR tracks mission success beyond logistics: progress, ownership, and completion risk.</p></div><div className="flex gap-2">{["ALL", "AT RISK", "WATCH", "ON TRACK"].map(filter => <button key={filter} onClick={() => setObjectiveFilter(filter)} className={`rounded-lg border px-2 py-1 text-[10px] ${objectiveFilter === filter ? "border-amber-400/50 text-amber-200 bg-amber-500/[.08]" : "border-slate-800 text-slate-500"}`}>{filter}</button>)}</div></div><div className="grid grid-cols-1 md:grid-cols-2 gap-3 mt-5">{visibleObjectives.map(item => <button key={item.id} onClick={() => setObjective(objective === item.id ? null : item.id)} className={`text-left rounded-xl border p-4 ${item.status === "AT RISK" ? "border-rose-500/35 bg-rose-500/[.04]" : "border-slate-800 bg-slate-950/60"}`}><div className="flex items-start justify-between gap-3"><div><div className="text-sm font-semibold text-slate-100">{item.label}</div><div className="text-[10px] text-slate-500 mt-1">Owner: {item.owner}</div></div><Badge variant="outline" className={item.status === "AT RISK" ? "border-rose-500/40 text-rose-300" : item.status === "WATCH" ? "border-amber-500/40 text-amber-300" : "border-emerald-500/40 text-emerald-300"}>{item.status}</Badge></div><div className="flex items-end justify-between mt-4"><div className="font-mono-tel text-3xl font-bold text-slate-100">{item.progress}%</div><div className="text-[10px] text-slate-500">{item.eta}</div></div><Progress value={item.progress} className="h-2 mt-3" /><div className="text-xs text-slate-400 mt-3">{item.detail}</div>{objective === item.id && <div className="mt-4 rounded-lg border border-amber-500/25 bg-amber-500/[.05] p-3 text-xs text-slate-300"><AlertTriangle className="inline h-3.5 w-3.5 text-amber-300 mr-1.5" />{item.status === "AT RISK" ? "Mission objective at risk: research team delayed by weather. Expected completion +2.4 days." : "Objective is being monitored against the active expedition plan."}</div>}</button>)}</div></section>
    <section className="rounded-2xl border border-slate-800 bg-slate-950/60 p-5"><div className="flex items-center gap-2"><ClipboardCheck className="h-4 w-4 text-emerald-300" /><div><h2 className="font-display text-lg font-bold">Mission success summary</h2><p className="text-xs text-slate-500 mt-1">Objective progress is now connected to the dependency tree.</p></div></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-4"><Summary label="Objectives on track" value="2 / 4" tone="emerald" /><Summary label="Objectives at risk" value="1" tone="rose" /><Summary label="Critical dependencies" value="3" tone="orange" /><Summary label="Overall mission progress" value="69%" tone="cyan" /></div></section>
  </div>;
}
function TreeNode({ node, depth, expanded, selected, onSelect, onToggle }) { const Icon = node.icon; const hasChildren = node.children?.length; return <div className="mb-1"><div className={`flex items-center gap-2 rounded-lg px-3 py-2 cursor-pointer ${selected === node.id ? "border border-cyan-400/40 bg-cyan-500/[.08]" : "hover:bg-white/[.03]"}`} style={{ marginLeft: depth * 22 }} onClick={() => onSelect(node.id)}><button onClick={event => { event.stopPropagation(); if (hasChildren) onToggle(node.id); }} className="w-4 text-slate-500">{hasChildren ? (expanded[node.id] ? "−" : "+") : "·"}</button><Icon className={`h-4 w-4 ${depth === 0 ? "text-cyan-300" : "text-slate-400"}`} /><span className={`text-sm ${depth === 0 ? "font-bold text-cyan-100" : "text-slate-200"}`}>{node.label}</span>{node.detail && <span className="ml-auto text-[10px] text-slate-600 hidden md:block">{node.detail}</span>}{selected === node.id && <ChevronRight className="ml-auto h-3.5 w-3.5 text-cyan-300" />}</div>{hasChildren && expanded[node.id] && <div className="border-l border-slate-800 ml-5">{node.children.map(child => <TreeNode key={child.id} node={child} depth={depth + 1} expanded={expanded} selected={selected} onSelect={onSelect} onToggle={onToggle} />)}</div>}</div>; }
function Summary({ label, value, tone }) { const colors = { emerald: "text-emerald-300 border-emerald-500/25", rose: "text-rose-300 border-rose-500/25", orange: "text-orange-300 border-orange-500/25", cyan: "text-cyan-300 border-cyan-500/25" }; return <div className={`rounded-xl border ${colors[tone]} bg-slate-950/60 p-4`}><div className="text-[10px] uppercase tracking-widest text-slate-500">{label}</div><div className={`font-mono-tel text-2xl font-bold mt-2 ${colors[tone].split(" ")[0]}`}>{value}</div></div>; }
