import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogFooter } from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { CloudSnow, Plus, RefreshCw, MapPin, Wind, Droplets, Thermometer, Clock3, Trash2 } from "lucide-react";

const EMPTY={name:"",latitude:"",longitude:""};
export default function Weather(){
  const [places,setPlaces]=useState([]); const [open,setOpen]=useState(false); const [form,setForm]=useState(EMPTY); const [loading,setLoading]=useState(false); const [autoRefresh,setAutoRefresh]=useState(true); const [intervalSec,setIntervalSec]=useState(60);
  const load=async()=>{try{setPlaces((await api.get("/weather/places")).data||[])}catch(e){toast.error(e.message||"Unable to load weather places.")}};
  useEffect(()=>{load()},[]);
  useEffect(()=>{if(!autoRefresh)return;const timer=setInterval(refresh,intervalSec*1000);return()=>clearInterval(timer)},[autoRefresh,intervalSec]);
  const add=async()=>{if(!form.name.trim()||form.latitude===""||form.longitude==="")return toast.error("Place name, latitude and longitude are required.");try{await api.post("/weather/places",{...form,latitude:Number(form.latitude),longitude:Number(form.longitude)});toast.success(`${form.name} added to weather monitoring`);setForm(EMPTY);setOpen(false);load()}catch(e){toast.error(e.message||"Unable to add place.")}};
  const refresh=async()=>{setLoading(true);try{const result=await api.post("/weather/refresh-all");setPlaces(result.data||[]);toast.success(`${result.updated} place(s) refreshed`)}catch(e){toast.error(e.message||"Weather service unavailable.")}finally{setLoading(false)}};
  const remove=async id=>{if(!window.confirm("Remove this weather place?"))return;try{await api.delete(`/weather/places/${id}`);setPlaces(rows=>rows.filter(row=>row.id!==id));toast.success("Weather place removed")}catch(e){toast.error(e.message||"Unable to remove place.")}};
  const refreshOne=async id=>{try{const result=await api.post(`/weather/places/${id}/refresh`);setPlaces(rows=>rows.map(row=>row.id===id?result.data:row));toast.success("Weather updated")}catch(e){toast.error(e.message||"Unable to refresh weather.")}};
  return <div className="p-4 md:p-8 space-y-6"><div className="flex items-start justify-between flex-wrap gap-4"><div><div className="text-[10px] font-mono-tel uppercase tracking-widest text-slate-500">Module · 02 / Environment</div><h1 className="font-display text-2xl md:text-3xl font-bold">Weather Management</h1><p className="text-sm text-slate-400 mt-1">Monitor temperature and conditions at multiple polar locations from one place.</p></div><div className="flex items-center gap-3 flex-wrap"><label className="flex items-center gap-2 text-xs text-slate-400"><input type="checkbox" checked={autoRefresh} onChange={e=>setAutoRefresh(e.target.checked)} className="accent-sky-500"/> Auto-refresh</label><select value={intervalSec} onChange={e=>setIntervalSec(Number(e.target.value))} className="h-9 rounded-md border border-slate-700 bg-slate-950 px-2 text-xs text-slate-300"><option value="30">30 sec</option><option value="60">1 min</option><option value="300">5 min</option></select><Button variant="outline" onClick={refresh} className="border-sky-500/40 text-sky-300"><RefreshCw className={`h-3.5 w-3.5 mr-1.5 ${loading?"animate-spin":""}`}/>Refresh all</Button><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="bg-sky-500 hover:bg-sky-400 text-slate-950"><Plus className="h-4 w-4 mr-1.5"/>Add place</Button></DialogTrigger><DialogContent className="bg-slate-950 border-slate-800 max-w-md"><DialogHeader><DialogTitle className="font-display">Add weather location</DialogTitle></DialogHeader><div className="space-y-3"><div><Label className="text-xs">Place name</Label><Input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Maitri Research Station"/></div><div className="grid grid-cols-2 gap-3"><div><Label className="text-xs">Latitude</Label><Input type="number" step="any" value={form.latitude} onChange={e=>setForm({...form,latitude:e.target.value})} placeholder="-70.77"/></div><div><Label className="text-xs">Longitude</Label><Input type="number" step="any" value={form.longitude} onChange={e=>setForm({...form,longitude:e.target.value})} placeholder="11.73"/></div></div><p className="text-[11px] text-slate-500">Use decimal coordinates. Example: Bharati Research Station is approximately -69.41, 76.19.</p></div><DialogFooter><Button onClick={add} className="bg-sky-500 hover:bg-sky-400 text-slate-950">Add and fetch weather</Button></DialogFooter></DialogContent></Dialog></div></div>
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Metric label="Monitored places" value={places.length} icon={MapPin}/><Metric label="Average temperature" value={places.length ? `${(places.reduce((sum,p)=>sum+Number(p.temperature_c||0),0)/places.length).toFixed(1)}°C` : "—"} icon={Thermometer}/><Metric label="Places with readings" value={places.filter(p=>p.temperature_c!==null&&p.temperature_c!==undefined).length} icon={CloudSnow}/><Metric label="Last update" value={latest(places)} icon={Clock3}/></div>
  {places.length===0?<div className="rounded-xl border border-dashed border-slate-800 p-12 text-center"><CloudSnow className="mx-auto h-10 w-10 text-sky-300 mb-3"/><div className="font-semibold text-slate-200">No weather places yet</div><div className="text-sm text-slate-500 mt-1">Add a station, vessel, camp, or any location using its coordinates.</div></div>:<div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">{places.map(place=><WeatherCard key={place.id} place={place} onRefresh={refreshOne} onRemove={remove}/>)}</div>}
  <div className="text-[11px] text-slate-500">Weather source: Open-Meteo. Readings are operational planning information and should be independently verified for safety-critical decisions.</div></div>
}
function WeatherCard({place,onRefresh,onRemove}){return <div className="rounded-xl border border-slate-800 bg-slate-950/70 p-5 hover-lift"><div className="flex items-start justify-between gap-3"><div><div className="text-[10px] uppercase tracking-widest text-slate-500">Monitored location</div><h2 className="font-display text-lg font-semibold text-slate-100 mt-1">{place.name}</h2><div className="text-[10px] text-slate-500 font-mono-tel mt-1">{Number(place.latitude).toFixed(3)}, {Number(place.longitude).toFixed(3)}</div></div><div className="flex items-center gap-2"><CloudSnow className="h-6 w-6 text-sky-300"/><Button size="sm" variant="ghost" onClick={()=>onRemove(place.id)} className="h-7 px-2 text-rose-300" title="Remove place"><Trash2 className="h-3.5 w-3.5"/></Button></div></div><div className="mt-5 flex items-end justify-between"><div><div className="font-mono-tel text-4xl font-bold text-sky-300">{place.temperature_c==null?"—":`${Number(place.temperature_c).toFixed(1)}°`}</div><div className="text-sm text-slate-300 mt-1">{place.conditions||"Awaiting reading"}</div></div><Badge variant="outline" className="border-emerald-500/40 text-emerald-300">LIVE</Badge></div><div className="grid grid-cols-3 gap-2 mt-5 pt-4 border-t border-slate-800"><Stat icon={Thermometer} label="Feels like" value={place.feels_like_c==null?"—":`${Number(place.feels_like_c).toFixed(1)}°`}/><Stat icon={Droplets} label="Humidity" value={place.humidity==null?"—":`${Math.round(place.humidity)}%`}/><Stat icon={Wind} label="Wind" value={place.wind_speed_kmh==null?"—":`${Math.round(place.wind_speed_kmh)} km/h`}/></div><div className="flex items-center justify-between mt-4"><div className="text-[10px] text-slate-500">Updated {place.last_updated?new Date(place.last_updated).toLocaleString():"not yet"}</div><Button size="sm" variant="ghost" onClick={()=>onRefresh(place.id)} className="text-sky-300"><RefreshCw className="h-3.5 w-3.5 mr-1"/>Update</Button></div></div>}
function Stat({icon:Icon,label,value}){return <div><div className="text-[10px] text-slate-500 flex items-center gap-1"><Icon className="h-3 w-3"/>{label}</div><div className="text-xs font-mono-tel text-slate-200 mt-1">{value}</div></div>}
function Metric({label,value,icon:Icon}){return <div className="rounded-xl border border-slate-800 bg-slate-950/70 p-4"><div className="flex justify-between text-[10px] font-mono-tel uppercase tracking-widest text-slate-500"><span>{label}</span><Icon className="h-4 w-4 text-sky-300"/></div><div className="mt-3 text-2xl font-mono-tel font-bold text-slate-100">{value}</div></div>}
function latest(rows){const dates=rows.map(row=>row.last_updated).filter(Boolean).sort();return dates.length?new Date(dates[dates.length-1]).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"}):"—"}
